### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Smx27** [MJ12358/flutter-template#1]
# Bug Report

Even though its a maintained project still im getting build failed 
Note: path is pinned to version 1.9.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because clean_flutter_architecture depends on flutter_localizations from sdk which depends on path 1.9.0, path 1.9.0 is required.
So, because clean_flutter_architecture depends on path 1.8.3, version solving failed.
exit code 1

**Comment by MJ12358** [comment]
I use Flutter version 3.13.9 to build, haven't tried on newer versions yet so that is most likely the cause.
A couple things you can try:

- Manually changing the version of `path` in `pubspec.yaml` to `1.9.0`, or if you don't want to pin versions just add a `^` in front of the version number
- Downgrading Flutter to version `3.13.9`

**Comment by Smx27** [comment]
I tried few ways to remidiate that but wont resolve the issue 
So i donwngraded my fluttwr version 
now its working on `3.13.9`
